export enum DataHubSubscriptionEventEnum {
  POST_CREATED_OPTIMISTIC = "POST_CREATED_OPTIMISTIC",
  POST_CREATED_PERSISTENT = "POST_CREATED_PERSISTENT",
  POST_UPDATED_OPTIMISTIC = "POST_UPDATED_OPTIMISTIC",
  POST_UPDATED_PERSISTENT = "POST_UPDATED_PERSISTENT",
  POST_FOLLOWED_OPTIMISTIC = "POST_FOLLOWED_OPTIMISTIC",
  POST_FOLLOWED_PERSISTENT = "POST_FOLLOWED_PERSISTENT",
  POST_UNFOLLOWED_OPTIMISTIC = "POST_UNFOLLOWED_OPTIMISTIC",
  POST_UNFOLLOWED_PERSISTENT = "POST_UNFOLLOWED_PERSISTENT",
  EVM_ADDRESS_LINKED_TO_ACCOUNT_OPTIMISTIC = "EVM_ADDRESS_LINKED_TO_ACCOUNT",
  EVM_ADDRESS_LINKED_TO_ACCOUNT_PERSISTENT = "EVM_ADDRESS_LINKED_TO_ACCOUNT",
  EVM_ADDRESS_UNLINKED_TO_ACCOUNT_OPTIMISTIC = "EVM_ADDRESS_UNLINKED_TO_ACCOUNT",
  EVM_ADDRESS_UNLINKED_TO_ACCOUNT_PERSISTENT = "EVM_ADDRESS_UNLINKED_TO_ACCOUNT",
}
